name: C/C++ CI

on:
  push:
    branches: [master]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make
        run: make ubuntu
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: TimestampAC-ubuntu
          path: TimestampAC

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make
        run: make macos
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: TimestampAC-macos
          path: TimestampAC

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build
        run: nmake windows
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: TimestampAC-windows.exe
          path: TimestampAC.exe
  release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-macos, build-windows]
    steps:
      - uses: actions/checkout@v2
      - name: Download Ubuntu Binary
        uses: actions/download-artifact@v2
        with:
          name: TimestampAC-ubuntu
          path: ubuntu
      - name: Download MacOS Binary
        uses: actions/download-artifact@v2
        with:
          name: TimestampAC-macos
          path: macos
      - name: Download Windows Binary
        uses: actions/download-artifact@v2
        with:
          name: TimestampAC-windows.exe
          path: windows
      - name: List files
        run: |
          dir
          cd ubuntu
          dir
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          artifacts: "TimestampAC-ubuntu,TimestampAC-macos,TimestampAC-windows.exe"
          tag: 1.0.0
