name: C/C++ CI

on:
  push:
    branches: [master]

jobs:
  build-ubuntu-18-04:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Make
        run: make linux
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: TimestampAC-ubuntu18.04
          path: TimestampAC
  build-ubuntu-20-04:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Make
        run: make linux
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: TimestampAC-ubuntu20.04
          path: TimestampAC

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make
        run: make macos
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: TimestampAC-macos
          path: TimestampAC

  build-windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Mingw
        run: sudo apt-get install mingw-w64
      - name: Build
        run: make windows
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: TimestampAC-windows.exe
          path: TimestampAC.exe
  release:
    runs-on: ubuntu-latest
    needs: [build-ubuntu-18-04, build-ubuntu-20-04, build-macos, build-windows]
    steps:
      - uses: actions/checkout@v2
      - name: Download Ubuntu 18.04 Binary
        uses: actions/download-artifact@v2
        with:
          name: TimestampAC-ubuntu18.04
          path: ubuntu18.04
      - name: Download Ubuntu 20.04 Binary
        uses: actions/download-artifact@v2
        with:
          name: TimestampAC-ubuntu20.04
          path: ubuntu20.04
      - name: Download MacOS Binary
        uses: actions/download-artifact@v2
        with:
          name: TimestampAC-macos
          path: macos
      - name: Download Windows Binary
        uses: actions/download-artifact@v2
        with:
          name: TimestampAC-windows.exe
          path: windows
      - name: List files
        run: |
          mv ubuntu18.04/TimestampAC TimestampAC-ubuntu18.04
          mv ubuntu20.04/TimestampAC TimestampAC-ubuntu20.04
          mv macos/TimestampAC TimestampAC-macos
          mv windows/TimestampAC.exe TimestampAC-windows.exe
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          artifacts: "TimestampAC-ubuntu18.04,TimestampAC-ubuntu20.04,TimestampAC-macos,TimestampAC-windows.exe"
          tag: 1.0.0
